const AUTH = {
	CHECK_USERNAME_AVAIL_ERROR: 'AUTH_CHECK_USERNAME_AVAIL_ERROR',
	CHECK_USERNAME_AVAIL_STARTED: 'AUTH_CHECK_USERNAME_AVAIL_STARTED',
	CHECK_USERNAME_AVAIL_SUCCESS: 'AUTH_CHECK_USERNAME_AVAIL_SUCCESS',
	RESET_USERNAME_STATUS: 'AUTH_RESET_USERNAME_STATUS',
	SESSION_EXTEND_ERROR: 'AUTH_SESSION_EXTEND_ERROR',
	SESSION_EXTEND_STARTED: 'AUTH_SESSION_EXTEND_STARTED',
	SESSION_EXTEND_SUCCESS: 'AUTH_SESSION_EXTEND_SUCCESS',
	SESSION_LOGIN_ERROR: 'AUTH_SESSION_LOGIN_ERROR',
	SESSION_LOGIN_STARTED: 'AUTH_SESSION_LOGIN_STARTED',
	SESSION_LOGIN_SUCCESS: 'AUTH_SESSION_LOGIN_SUCCESS',
	SESSION_LOGOUT_ERROR: 'AUTH_SESSION_LOGOUT_ERROR',
	SESSION_LOGOUT_STARTED: 'AUTH_SESSION_LOGOUT_STARTED',
	SESSION_LOGOUT_SUCCESS: 'AUTH_SESSION_LOGOUT_SUCCESS'
};

const ETHEREUM = {
	CLEAR_BALANCE: 'ETHEREUM_CLEAR_BALANCE',
	CLEAR_TRANSACTIONS: 'ETHEREUM_CLEAR_TRANSACTIONS',
	UPDATE_BALANCE_ERROR: 'ETHEREUM_UPDATE_BALANCE_ERROR',
	UPDATE_BALANCE_STARTED: 'ETHEREUM_UPDATE_BALANCE_STARTED',
	UPDATE_BALANCE_SUCCESS: 'ETHEREUM_UPDATE_BALANCE_SUCCESS',
	UPDATE_TRANSACTIONS_ERROR: 'ETHEREUM_UPDATE_TRANSACTIONS_ERROR',
	UPDATE_TRANSACTIONS_STARTED: 'ETHEREUM_UPDATE_TRANSACTIONS_STARTED',
	UPDATE_TRANSACTIONS_SUCCESS: 'ETHEREUM_UPDATE_TRANSACTIONS_SUCCESS'
};

const NETWORK = {
	CHECK_CONNECTIVITY_ERROR: 'NETWORK_CHECK_CONNECTIVITY_ERROR',
	CHECK_CONNECTIVITY_STARTED: 'NETWORK_CHECK_CONNECTIVITY_STARTED',
	CHECK_CONNECTIVITY_SUCCESS: 'NETWORK_CHECK_CONNECTIVITY_SUCCESS',
	RESET_CONNECTIVITY_STATUS: 'NETWORK_RESET_CONNECTIVITY_STATUS'
};

const SETTINGS = {
	RESET: 'SETTINGS_RESET',
	SET_CURRENCY: 'SETTINGS_SET_CURRENCY',
	TOGGLE_NIGHT_MODE: 'SETTINGS_TOGGLE_NIGHT_MODE'
};

const USER = {
	CLEAR_ALL: 'USER_CLEAR_ALL',
	SET_ADDRESS_ERROR: 'USER_SET_ADDRESS_ERROR',
	SET_ADDRESS_STARTED: 'USER_SET_ADDRESS_STARTED',
	SET_ADDRESS_SUCCESS: 'USER_SET_ADDRESS_SUCCESS',
	SET_AVATAR_ERROR: 'USER_SET_AVATAR_ERROR',
	SET_AVATAR_STARTED: 'USER_SET_AVATAR_STARTED',
	SET_AVATAR_SUCCESS: 'USER_SET_AVATAR_SUCCESS',
	SET_COUNTRY_ERROR: 'USER_SET_COUNTRY_ERROR',
	SET_COUNTRY_STARTED: 'USER_SET_COUNTRY_STARTED',
	SET_COUNTRY_SUCCESS: 'USER_SET_COUNTRY_SUCCESS',
	SET_EMAIL_ERROR: 'USER_SET_EMAIL_ERROR',
	SET_EMAIL_STARTED: 'USER_SET_EMAIL_STARTED',
	SET_EMAIL_SUCCESS: 'USER_SET_EMAIL_SUCCESS',
	SET_NAME_ERROR: 'USER_SET_NAME_ERROR',
	SET_NAME_STARTED: 'USER_SET_NAME_STARTED',
	SET_NAME_SUCCESS: 'USER_SET_NAME_SUCCESS',
	SET_NUMBER_ERROR: 'USER_SET_NUMBER_ERROR',
	SET_NUMBER_STARTED: 'USER_SET_NUMBER_STARTED',
	SET_NUMBER_SUCCESS: 'USER_SET_NUMBER_SUCCESS',
	UPDATE_ERROR: 'USER_UPDATE_ERROR',
	UPDATE_STARTED: 'USER_UPDATE_STARTED',
	UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS'
};

export { AUTH, ETHEREUM, NETWORK, SETTINGS, USER };
