const AUTH = {
	SESSION_TOKEN_CLEAR: 'AUTH_SESSION_TOKEN_CLEAR',
	SESSION_TOKEN_ERROR: 'AUTH_SESSION_TOKEN_ERROR',
	SESSION_TOKEN_STARTED: 'AUTH_SESSION_TOKEN_STARTED',
	SESSION_TOKEN_SUCCESS: 'AUTH_SESSION_TOKEN_SUCCESS'
};

const ETHEREUM = {
	CLEAR_BALANCE: 'ETHEREUM_CLEAR_BALANCE',
	CLEAR_TRANSACTIONS: 'ETHEREUM_CLEAR_TRANSACTIONS',
	UPDATE_BALANCE_ERROR: 'ETHEREUM_UPDATE_BALANCE_ERROR',
	UPDATE_BALANCE_STARTED: 'ETHEREUM_UPDATE_BALANCE_STARTED',
	UPDATE_BALANCE_SUCCESS: 'ETHEREUM_UPDATE_BALANCE_SUCCESS',
	UPDATE_CURRENCY_RATES_ERROR: 'ETHEREUM_UPDATE_CURRENCY_RATES_ERROR',
	UPDATE_CURRENCY_RATES_STARTED: 'ETHEREUM_UPDATE_CURRENCY_RATES_STARTED',
	UPDATE_CURRENCY_RATES_SUCCESS: 'ETHEREUM_UPDATE_CURRENCY_RATES_SUCCESS',
	UPDATE_TRANSACTIONS_ERROR: 'ETHEREUM_UPDATE_TRANSACTIONS_ERROR',
	UPDATE_TRANSACTIONS_STARTED: 'ETHEREUM_UPDATE_TRANSACTIONS_STARTED',
	UPDATE_TRANSACTIONS_SUCCESS: 'ETHEREUM_UPDATE_TRANSACTIONS_SUCCESS'
};

const SETTINGS = {
	RESET: 'SETTINGS_RESET',
	SET_CURRENCY: 'SETTINGS_SET_CURRENCY',
	SET_API_KEY: 'SETTINGS_SET_API_KEY',
	TOGGLE_NIGHT_MODE: 'SETTINGS_TOGGLE_NIGHT_MODE'
};

const USER = {
	CLEAR_ALL: 'USER_CLEAR_ALL',
	SET_ADDRESS: 'USER_SET_ADDRESS'
};

export { AUTH, ETHEREUM, SETTINGS, USER };
